server:
  forward-headers-strategy: native
  port: 8081
spring:
  application:
    name: main-server
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresmainservice:5432/main-db
    username: postgres
    password: postgres
  jpa:
    openInView: true
    show-sql: false
    generateDdl: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  boot:
    admin:
      context-path: /admin-ui
      ui:
        public-url: /admin-ui/
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
      instance:
        preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always