server:
  forward-headers-strategy: native
  port: 8081
minio:
  url: ${MINIO_URL:http://localhost:9000}
  bucket: ${MINIO_BUCKET:file-storage}
  username: ${MINIO_USERNAME:minioadmin}
  password: ${MINIO_PASSWORD:minioadmin}
spring:
  application:
    name: main-server
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_ADDRESS:localhost}:5432/main-final
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:123}
  jpa:
    openInView: true
    show-sql: false
    generateDdl: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  boot:
    admin:
      context-path: /admin-ui
      ui:
        public-url: /admin-ui/
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ADDRESS:localhost}:8761/eureka
      instance:
        preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
init-db: ${INIT_DB:true}